# Generated by Django 4.0.4 on 2022-06-08 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0005_alter_connection_source_alter_connection_supplychain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_batch_product_alter_batch_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('body', models.CharField(default='', max_length=500)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('action_push', models.BooleanField(default=False)),
                ('action_sms', models.BooleanField(default=False)),
                ('action_email', models.BooleanField(default=False)),
                ('event', models.CharField(max_length=255)),
                ('event_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('context', models.JSONField(blank=True, null=True)),
                ('send_to', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('actor_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='nodes.node')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('supply_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplychain')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='nodes.node')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
