# Generated by Django 4.0.4 on 2022-06-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0016_supplychain'),
        ('notifications', '0002_notification_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='supply_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply_chains.supplychain'),
        ),
    ]
