# Generated by Django 4.0.4 on 2022-06-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_accesstoken_user_alter_userdevice_user_and_more'),
        ('notifications', '0003_alter_notification_supply_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='validation_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='accounts.validationtoken'),
        ),
    ]
