# Generated by Django 4.0.4 on 2022-07-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0005_notification_content_type_notification_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_event_types', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
