# Generated by Django 4.0.4 on 2022-07-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
