# Generated by Django 4.0.4 on 2022-07-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_redirect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
