# Generated by Django 4.0.4 on 2022-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_redirect_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_en_uk',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='body_en_us',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='body_fr',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='body_nl',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en_uk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en_us',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_fr',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_nl',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
