# Generated by Django 4.0.4 on 2023-01-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_body_en_uk_notification_body_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='aws_sms_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
