# Generated by Django 4.0.4 on 2023-01-12 07:51

from django.db import migrations


def change_notification_slug(apps, schema_editor):
    from django.db.models import Q
    Notification = apps.get_model('notifications', 'Notification')
    slugs_to_change = {
        "node_document": "node_document_added",
        "attached_claim_comment": "added_claim_comment",
        "transaction_created": "transaction_received"
    }
    for k, v in slugs_to_change.items():
        Notification.objects.filter(type=k).update(type=v)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_aws_sms_id'),
    ]

    operations = [
        migrations.RunPython(change_notification_slug),
    ]
