# Generated by Django 4.0.4 on 2023-01-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_update_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('password_reset', 'Password reset'), ('member_invite', 'Member Invite'), ('node_document_added', 'Document Added'), ('node_invite', 'Node Invite'), ('transaction_sent', 'Transaction Sent'), ('transaction_received', 'Transaction Received'), ('transaction_approval', 'Transaction Approval'), ('transaction_comment', 'Transaction Comment'), ('purchase_order_create', 'Purchase Order Create'), ('purchase_order_update', 'Purchase Order Update'), ('purchase_order_approval', 'Purchase Order Approval'), ('delivery_notification', 'Delivery Notification'), ('claim_attachment', 'Claim Attached'), ('claim_verification', 'Claim Verified'), ('added_claim_comment', 'Claim Comment Added'), ('bulk_upload_completed', 'Bulk Upload Complete')], max_length=100),
        ),
    ]
