# Generated by Django 4.0.4 on 2023-01-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_smsalerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsalerts',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsalerts',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsalerts',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
