# Generated by Django 4.0.4 on 2022-05-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_blocked_validationtoken_userdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdevice', verbose_name='Created Device'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='key',
            field=models.CharField(max_length=200, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='Token User'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='type',
            field=models.IntegerField(choices=[(101, 'Android'), (102, 'Ios'), (103, 'Web')], default=101, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Device User'),
        ),
        migrations.AlterField(
            model_name='validationtoken',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Token Expiry Date'),
        ),
        migrations.AlterField(
            model_name='validationtoken',
            name='key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='validationtoken',
            name='status',
            field=models.IntegerField(choices=[(101, 'Used'), (111, 'Unused')], default=111, verbose_name='Token Status'),
        ),
        migrations.AlterField(
            model_name='validationtoken',
            name='type',
            field=models.IntegerField(choices=[(101, 'Verify Email'), (102, 'Change Email'), (103, 'Reset Password'), (104, 'OTP'), (105, 'Magic Login'), (106, 'Invite'), (107, 'Notification')], default=101, verbose_name='Token Type'),
        ),
        migrations.AlterField(
            model_name='validationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Token User'),
        ),
    ]
