# Generated by Django 4.0.4 on 2022-05-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accesstoken_created_alter_accesstoken_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authe_token', to=settings.AUTH_USER_MODEL, verbose_name='Token User'),
        ),
    ]
