# Generated by Django 4.0.4 on 2022-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userdevice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='name',
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
