# Generated by Django 4.0.4 on 2022-05-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_subdomain'),
        ('supply_chains', '0013_alter_nodemember_user'),
        ('accounts', '0008_customuser_default_node_customuser_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_node_users', to='supply_chains.node', verbose_name='Default Node Of User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
