# Generated by Django 4.0.4 on 2022-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_accesstoken_user_alter_userdevice_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='blocked',
            new_name='is_blocked',
        ),
    ]
