# Generated by Django 4.0.4 on 2022-07-23 12:55

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', base.models.CustomUserManager()),
            ],
        ),
    ]
