# Generated by Django 4.0.4 on 2022-08-02 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_address_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='Policy Content')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Privacy Policy Date')),
                ('since', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_users', to='accounts.privacypolicy', verbose_name='Latest Accepted Privacy Policy'),
        ),
    ]
