# Generated by Django 4.0.4 on 2022-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_privacypolicy_customuser_accepted_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='version',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Version'),
        ),
    ]
