# Generated by Django 4.0.4 on 2022-08-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_privacypolicy_options_alter_privacypolicy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_logout',
            field=models.BooleanField(default=False, verbose_name='Force Logout User'),
        ),
    ]
