# Generated by Django 4.0.4 on 2022-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_force_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='content_en_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Policy Content'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content_en_us',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Policy Content'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Policy Content'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content_nl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Policy Content'),
        ),
    ]
