# Generated by Django 4.0.4 on 2023-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_accesstoken_user_alter_userdevice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='walkthrough_status',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='WalkThrough Status'),
        ),
    ]
