# Generated by Django 4.0.4 on 2023-11-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_validationtoken_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationtoken',
            name='type',
            field=models.IntegerField(choices=[(101, 'Verify Email'), (102, 'Change Email'), (103, 'Reset Password'), (104, 'OTP'), (105, 'Magic Login'), (106, 'Invite'), (107, 'Notification'), (108, 'Questionnaire Share'), (109, 'Questionnaire Link')], default=101, verbose_name='Token Type'),
        ),
    ]
