# Generated by Django 4.0.4 on 2022-05-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_country_options_country_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
