# Generated by Django 4.0.4 on 2022-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenantadmin_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default='default', max_length=32, unique=True, verbose_name='Tenant subdomain'),
            preserve_default=False,
        ),
    ]
