# Generated by Django 4.0.4 on 2022-06-02 22:50

from django.db import migrations

from common.country_data import COUNTRIES


def populate_country_and_province_data(apps, schema_editor):
    Country = apps.get_model('tenants', 'Country')
    Province = apps.get_model('tenants', 'Province')
    for country_name, extra_data in list(COUNTRIES.items()):
        country, _ = Country.objects.get_or_create(
            name=country_name)
        country.latitude = extra_data['latlong'][0]
        country.longitude = extra_data['latlong'][1]
        country.code = extra_data['alpha_2']
        country.dial_code = extra_data['dial_code']
        country.save()
        for province_name, loc_data in list(
            extra_data['sub_divisions'].items()):
            province, _ = Province.objects.get_or_create(
            name=province_name, country=country)
            province.latitude = loc_data['latlong'][0]
            province.longitude = loc_data['latlong'][1]
            province.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_remove_country_provinces_remove_country_tenant_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_country_and_province_data)
    ]
