# Generated by Django 4.0.4 on 2022-06-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_auto_20220602_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['country__name']},
        ),
    ]
