# Generated by Django 4.0.4 on 2022-06-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_alter_formsubmission_node'),
        ('tenants', '0013_alter_country_options_alter_province_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='claim_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_tenant', to='dynamic_forms.form', verbose_name='Extra Fields For Claim'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='node_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_tenant', to='dynamic_forms.form', verbose_name='Extra Fields For Node'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='node_member_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_member_tenant', to='dynamic_forms.form', verbose_name='Extra Fields For Node Member'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='transaction_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_tenant', to='dynamic_forms.form', verbose_name='Extra Fields For Transaction'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='txn_enquiry_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txn_enquiry_tenant', to='dynamic_forms.form', verbose_name='Extra Fields For Transaction Enquiry'),
        ),
    ]
