# Generated by Django 4.0.4 on 2022-06-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_alter_province_country_alter_tenantadmin_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='connection_auto_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='connection_disabling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mandatory_transaction_claims',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='transaction_auto_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='transaction_rejection',
            field=models.BooleanField(default=True),
        ),
    ]
