# Generated by Django 4.0.4 on 2022-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_auto_20220620_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='currencies',
            field=models.ManyToManyField(related_name='tenants', to='tenants.currency', verbose_name='Currencies'),
        ),
    ]
