# Generated by Django 4.0.4 on 2022-07-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
