# Generated by Django 4.0.4 on 2022-07-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_unit_tenant'),
        ('tenants', '0022_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='units',
            field=models.ManyToManyField(related_name='tenants', to='products.unit', verbose_name='Units'),
        ),
    ]
