# Generated by Django 4.0.4 on 2022-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_tenant_block_chain_request_tenant_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='batch_claim',
            field=models.BooleanField(default=True, verbose_name='Is Batch Claim Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bulk_upload',
            field=models.BooleanField(default=False, verbose_name='Bulk Upload Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_claim',
            field=models.BooleanField(default=True, verbose_name='Is Company Claim Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mobile_app',
            field=models.BooleanField(default=False, verbose_name='Is Mobile App Enabled'),
        ),
    ]
