# Generated by Django 4.0.4 on 2022-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_rename_company_claim_tenant_node_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Currency Name'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Currency Name'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Currency Name'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Currency Name'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Province Name'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Province Name'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Province Name'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Province Name'),
        ),
    ]
