# Generated by Django 4.0.4 on 2022-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_category_name_en_uk_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name_en_uk',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name_en_uk',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='province',
            name='name_en_uk',
        ),
        migrations.RemoveField(
            model_name='province',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='province',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='province',
            name='name_nl',
        ),
    ]
