# Generated by Django 4.0.4 on 2022-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_remove_tenant_transaction_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('de', 'German'), ('fr', 'French')], default='en', max_length=10, verbose_name='Selected Language'),
        ),
    ]
