# Generated by Django 4.0.4 on 2022-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_country_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='non_producer_stock_creation',
            field=models.BooleanField(default=False, verbose_name='Non Producer can create stock'),
        ),
    ]
