# Generated by Django 4.0.4 on 2023-01-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0034_rename_code_country_alpha_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha_3',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='CCA3 Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha_2',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Country Code'),
        ),
    ]
