# Generated by Django 4.0.4 on 2023-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_country_alpha_2_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='risk_analysis',
            field=models.BooleanField(default=True, verbose_name='Is Risk Analysis Enabled'),
        ),
    ]
