# Generated by Django 4.0.4 on 2023-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0037_tenant_risk_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='symmetrical_connection',
            field=models.BooleanField(default=True),
        ),
    ]
