# Generated by Django 4.0.4 on 2023-01-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0040_auto_20230105_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='NA', max_length=1000, verbose_name='Country Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='NA', max_length=1000, verbose_name='Currency Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='tenants.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(default='NA', max_length=1000, verbose_name='Province Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='NA', max_length=1000, verbose_name='Region Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='tenants.province', verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(default='NA', max_length=1000, verbose_name='Village Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='village',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='tenants.region', verbose_name='Region'),
            preserve_default=False,
        ),
    ]
