# Generated by Django 4.0.4 on 2023-05-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0043_tenant_env_data_form_tenant_gov_data_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='product_grouping',
            field=models.BooleanField(default=False, verbose_name='Is Product Grouping Enabled'),
        ),
    ]
