# Generated by Django 4.0.4 on 2023-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0044_tenant_product_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='connection_claim',
            field=models.BooleanField(default=True, verbose_name='Is Connection Claim Enabled'),
        ),
    ]
