# Generated by Django 4.0.4 on 2023-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0046_alter_category_tenant_alter_tenantadmin_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='node_data_transparency',
            field=models.IntegerField(choices=[(101, 'Fully Transparent'), (111, 'Partialy Transparent')], default=101, verbose_name='Node Data Transparency'),
        ),
    ]
