# Generated by Django 4.0.4 on 2023-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0047_tenant_node_data_transparency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_empty_batches',
            field=models.BooleanField(default=True, verbose_name='Show empty batches Tab'),
        ),
    ]
