# Generated by Django 4.0.4 on 2023-08-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0048_tenant_show_empty_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
