# Generated by Django 4.0.4 on 2023-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0049_country_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='questionnaire',
            field=models.BooleanField(default=False, verbose_name='Is Questionnaire Enabled'),
        ),
    ]
