# Generated by Django 4.0.4 on 2023-11-22 07:22

from django.db import migrations


def move_tags_from_suppy_chains_to_tenants(apps, schema_editor):
    """Move tags from the tag model in supplychain to tag model in tenants"""
    SUPLLY_TAG = apps.get_model('supply_chains', 'Tag')
    TENANT_TAG = apps.get_model('tenants', 'Tag')
    supply_tags = SUPLLY_TAG.objects.all()
    for supply_tag in supply_tags:
        data = supply_tag.__dict__
        data.pop('_state')
        data['is_deleted'] = data.pop('is_blocked')
        TENANT_TAG.objects.create(**supply_tag.__dict__)

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0051_tag'),
    ]

    operations = [
        migrations.RunPython(move_tags_from_suppy_chains_to_tenants)
    ]
