# Generated by Django 4.0.4 on 2022-06-01 10:49

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_tenant_subdomain'),
        ('supply_chains', '0013_alter_nodemember_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_forms', '0004_alter_formfieldvalue_form'),
        ('products', '0003_alter_unit_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('house_name', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=500)),
                ('sub_province', models.CharField(blank=True, default='', max_length=500)),
                ('province', models.CharField(blank=True, default='', max_length=500)),
                ('country', models.CharField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('zipcode', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Node')),
                ('registration_no', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Node Registartion Number')),
                ('type', models.IntegerField(choices=[(101, 'Company'), (111, 'Farmer')], default=101, verbose_name='Node Type')),
                ('contact_name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Contact Person Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Name')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone Number')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Description')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=common.library._get_file_path, verbose_name='Photo')),
                ('invited_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Invited Date')),
                ('joined_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Joining Date')),
                ('status', models.IntegerField(choices=[(101, 'Active'), (111, 'Inactive')], default=111, verbose_name='Node Current Status')),
                ('verified', models.BooleanField(default=False, verbose_name='Is Node Verified')),
                ('is_producer', models.BooleanField(default=False, verbose_name='Is Node Producer')),
                ('is_verifier', models.BooleanField(default=False, verbose_name='Is Node Verifier')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_node', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data')),
                ('operations', models.ManyToManyField(blank=True, default=None, related_name='nodes', to='supply_chains.operation', verbose_name='Categories')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(101, 'Admin'), (111, 'Operator'), (121, 'Certifier'), (131, 'Verifier'), (141, 'Creator')], default=101, verbose_name='Member Type')),
                ('active', models.BooleanField(default=False, verbose_name='Is Member Active')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_member', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='nodes.node', verbose_name='Node')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_members', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='Member User')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=500, verbose_name='File Name')),
                ('description', models.CharField(default='', max_length=2000, verbose_name='File Description')),
                ('file', models.FileField(blank=True, default=None, max_length=500, null=True, upload_to=common.library._get_file_path, verbose_name='Document')),
                ('type', models.IntegerField(choices=[(101, 'Company Document')], default=101, verbose_name='Document Type')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is File Deleted')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nodes.node', verbose_name='Node')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('graph_id', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='GraphDB Id')),
                ('status', models.IntegerField(choices=[(101, 'Active'), (111, 'Inactive'), (121, 'Blocked')], default=111, verbose_name='Connection Status')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='nodes.node', verbose_name='Connected From')),
                ('source_tags', models.ManyToManyField(related_name='source_connections', to='supply_chains.tag', verbose_name='Source Node Tags')),
                ('supplychain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='products.supplychain', verbose_name='Supplychain')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_connections', to='nodes.node', verbose_name='Connected To')),
                ('target_tags', models.ManyToManyField(related_name='target_connections', to='supply_chains.tag', verbose_name='Source Node Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nodes.node')),
                ('incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
            bases=('nodes.node',),
        ),
    ]
