# Generated by Django 4.0.4 on 2022-06-01 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_default_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='members',
            field=models.ManyToManyField(related_name='nodes', through='nodes.NodeMember', to=settings.AUTH_USER_MODEL, verbose_name='Member Nodes'),
        ),
        migrations.AlterField(
            model_name='nodemember',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_members', to='nodes.node', verbose_name='Node'),
        ),
        migrations.AlterField(
            model_name='nodemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Member User'),
        ),
    ]
