# Generated by Django 4.0.4 on 2022-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_members_alter_nodemember_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Node Name'),
        ),
    ]
