# Generated by Django 4.0.4 on 2022-06-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_remove_country_provinces_remove_country_tenant_and_more'),
        ('nodes', '0003_alter_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_nodes', to='tenants.country', verbose_name='Country of Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_nodes', to='tenants.province', verbose_name='Province of Node'),
        ),
    ]
