# Generated by Django 4.0.4 on 2022-06-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0015_alter_tag_tenant'),
        ('nodes', '0005_alter_connection_source_alter_connection_supplychain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='operations',
        ),
        migrations.AddField(
            model_name='node',
            name='operation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='supply_chains.operation', verbose_name='Categories'),
        ),
    ]
