# Generated by Django 4.0.4 on 2022-06-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0016_supplychain'),
        ('nodes', '0006_remove_node_operations_node_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='supplychain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='supply_chains.supplychain', verbose_name='Supplychain'),
        ),
    ]
