# Generated by Django 4.0.4 on 2022-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_delete_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='form',
            new_name='submission_form',
        ),
        migrations.RenameField(
            model_name='nodemember',
            old_name='form',
            new_name='submission_form',
        ),
    ]
