# Generated by Django 4.0.4 on 2022-06-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0013_alter_node_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='nodemember',
            old_name='active',
            new_name='is_active',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
