# Generated by Django 4.0.4 on 2022-06-20 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_alter_currency_options_tenant_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0015_node_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_nodes', to='tenants.currency', verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='node',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Incharge'),
        ),
    ]
