# Generated by Django 4.0.4 on 2022-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0016_node_currency_alter_node_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedocument',
            name='type',
            field=models.IntegerField(choices=[(101, 'Company Document'), (102, 'Incorporation Document'), (103, 'Certification'), (104, 'Annual Report')], default=101, verbose_name='Document Type'),
        ),
    ]
