# Generated by Django 4.0.4 on 2022-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0017_alter_nodedocument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Member Active'),
        ),
    ]
