# Generated by Django 4.0.4 on 2022-07-04 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0020_alter_nodemember_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodemember',
            options={},
        ),
        migrations.AddField(
            model_name='node',
            name='is_discoverable',
            field=models.BooleanField(default=True, verbose_name='Is Node Discoverable To Others'),
        ),
        migrations.AddField(
            model_name='node',
            name='visibility',
            field=models.IntegerField(choices=[(101, 'Tenant Specific'), (111, 'Visible'), (121, 'Fully Anonymous')], default=101, verbose_name='Node Visibility'),
        ),
        migrations.AlterUniqueTogether(
            name='nodemember',
            unique_together={('node', 'user')},
        ),
    ]
