# Generated by Django 4.0.4 on 2022-07-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_alter_category_options'),
        ('nodes', '0021_alter_nodemember_options_node_is_discoverable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodedocument',
            name='type',
        ),
        migrations.AddField(
            model_name='nodedocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='tenants.category', verbose_name='Document Category'),
        ),
    ]
