# Generated by Django 4.0.4 on 2022-07-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0030_alter_nodesupplychain_options_and_more'),
        ('nodes', '0022_remove_nodedocument_type_nodedocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemember',
            name='default_supply_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_supplychain_members', to='supply_chains.supplychain', verbose_name='Default Supplychain Of Member'),
        ),
    ]
