# Generated by Django 4.0.4 on 2022-07-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0022_remove_nodedocument_type_nodedocument_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='country',
        ),
    ]
