# Generated by Django 4.0.4 on 2022-07-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0023_nodemember_default_supply_chain'),
        ('nodes', '0023_remove_node_country'),
    ]

    operations = [
    ]
