# Generated by Django 4.0.4 on 2022-07-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0024_merge_20220719_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='city',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='node',
            name='house_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='node',
            name='street',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='sub_province',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nodedocument',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='File Description'),
        ),
        migrations.AlterField(
            model_name='nodedocument',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='File Name'),
        ),
    ]
