# Generated by Django 4.0.4 on 2022-08-15 17:31

from django.db import migrations, models
import functools
import utilities.function_generators


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0025_alter_node_city_alter_node_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='trace_code',
            field=models.CharField(default=functools.partial(utilities.function_generators.formatter, *('RO{y}-{R10}',), **{}), max_length=500, verbose_name='Right Origins Traceability Code'),
        ),
    ]
