# Generated by Django 4.0.4 on 2022-08-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0026_alter_node_trace_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_nodes', to='nodes.node', verbose_name='Invited By'),
        ),
    ]
