# Generated by Django 4.0.4 on 2022-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0027_node_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='upload_timestamp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Upload Id'),
        ),
    ]
