# Generated by Django 4.0.4 on 2023-01-16 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0040_auto_20230105_1142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0029_node_inviter_questionnaire_node_ro_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemember',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='node_members', to='nodes.node', verbose_name='Node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodemember',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='node_members', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodemember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Member User'),
            preserve_default=False,
        ),
    ]
