# Generated by Django 4.0.4 on 2023-02-23 14:20

from django.db import migrations, models
import functools
import utilities.function_generators


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0030_alter_nodemember_node_alter_nodemember_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='connect_id',
            field=models.CharField(default=functools.partial(utilities.function_generators.formatter, *('{r5}-{r5}-{r5}',), **{}), max_length=100, verbose_name='Connect-ID. Used to securely connect to a un related node.'),
        ),
    ]
