# Generated by Django 4.0.4 on 2023-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0034_alter_node_env_data_alter_node_gov_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='env_data_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Environment Data Mongo Submission Id'),
        ),
        migrations.AddField(
            model_name='node',
            name='gov_data_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Governance Data Mongo Submission Id'),
        ),
        migrations.AddField(
            model_name='node',
            name='inviter_questionnaire_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Inviter Questionnaire Mongo Submission Id'),
        ),
        migrations.AddField(
            model_name='node',
            name='signup_questionnaire_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='SignUp Questionnaire Mongo Submission Id'),
        ),
        migrations.AddField(
            model_name='node',
            name='soc_data_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Scial Data Mongo Submission Id'),
        ),
        migrations.AddField(
            model_name='node',
            name='submission_form_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='MongoDB Form Submission Id'),
        ),
    ]
