# Generated by Django 4.0.4 on 2023-07-05 11:32

import common.library
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0046_alter_category_tenant_alter_tenantadmin_tenant_and_more'),
        ('nodes', '0035_node_env_data_mongo_id_node_gov_data_mongo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodedocument',
            name='file',
            field=models.FileField(default=None, max_length=500, upload_to=common.library._get_file_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='nodedocument',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nodes.node', verbose_name='Node'),
            preserve_default=False,
        ),
    ]
