# Generated by Django 4.0.4 on 2023-11-02 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0046_merge_20230918_0703'),
        ('nodes', '0036_alter_node_tenant_alter_nodedocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedocument',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='nodedocument',
            name='synced_to',
            field=models.IntegerField(blank=True, choices=[(101, 'RO AI')], default=None, null=True, verbose_name='Document Synced To'),
        ),
        migrations.AddField(
            model_name='nodedocument',
            name='tags',
            field=models.ManyToManyField(related_name='node_documents', to='supply_chains.tag', verbose_name='Node Document Tags'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Folder Name')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Folder Deleted')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='nodes.node', verbose_name='Node')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='nodes.folder', verbose_name='Parent Folder')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('node', 'parent_folder', 'name')},
            },
        ),
        migrations.AddField(
            model_name='nodedocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='nodes.folder', verbose_name='Folder'),
        ),
    ]
