# Generated by Django 4.0.4 on 2023-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0037_nodedocument_expiry_date_nodedocument_synced_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='company_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Company Website Url'),
        ),
    ]
