# Generated by Django 4.0.4 on 2023-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0052_auto_20231122_0722'),
        ('nodes', '0039_alter_nodedocument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedocument',
            name='tags',
            field=models.ManyToManyField(related_name='node_documents', to='tenants.tag', verbose_name='Node Document Tags'),
        ),
    ]
