# Generated by Django 4.0.4 on 2024-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0040_alter_nodedocument_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedocument',
            name='openai_file_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Open AI File ID'),
        ),
    ]
