# Generated by Django 4.0.4 on 2023-01-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0029_node_inviter_questionnaire_node_ro_number_and_more'),
        ('risk', '0002_riskscore_environment_riskscore_governance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskscore',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='nodes.node', verbose_name='Node'),
        ),
    ]
