# Generated by Django 4.0.4 on 2022-05-16 19:09

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenantadmin_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template Name')),
                ('title_row', models.IntegerField(blank=True, default=0, null=True, verbose_name='Title Row Starting')),
                ('data_row', models.IntegerField(blank=True, default=0, null=True, verbose_name='Data Row Starting')),
                ('file', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Template')),
                ('type', models.IntegerField(choices=[(101, 'Transaction'), (111, 'Connection')], default=101, verbose_name='Template Type')),
                ('default', models.BooleanField(default=False, verbose_name='Is Default Template')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Template Deleted')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('required', models.BooleanField(default=False, verbose_name='Is Field Required')),
                ('name', models.CharField(max_length=500, verbose_name='Name Of Field')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description About Field')),
                ('template_type', models.IntegerField(choices=[(101, 'Transaction'), (111, 'Connection')], default=101, verbose_name='Template Type')),
                ('type', models.IntegerField(choices=[(101, 'String'), (111, 'Integer'), (121, 'Float'), (131, 'Date'), (141, 'Phone'), (151, 'Email'), (161, 'Paragraph'), (171, 'Currency'), (181, 'Unit')], default=101, verbose_name='Field Type')),
                ('key', models.CharField(max_length=1000, verbose_name='Field Key Name')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('column_pos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Column Position')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_field', to='bulk_templates.templatefieldtype', verbose_name='Field')),
                ('template', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='bulk_templates.template', verbose_name='Template')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Excel File')),
                ('data', models.JSONField(blank=True, default=list, null=True, verbose_name='Data')),
                ('errors', models.JSONField(blank=True, default=list, null=True, verbose_name='Error Data')),
                ('farmers_to_add', models.IntegerField(default=0, verbose_name='Total Producers To Add')),
                ('farmers_added', models.IntegerField(default=0, verbose_name='Total Producers Added')),
                ('farmers_to_update', models.IntegerField(default=0, verbose_name='Total Producers To Update')),
                ('farmers_updated', models.IntegerField(default=0, verbose_name='Total Producers Updated')),
                ('transactions_to_add', models.IntegerField(default=0, verbose_name='Total Transactions To Add')),
                ('transactions_added', models.IntegerField(default=0, verbose_name='Total Transactions Added')),
                ('used', models.BooleanField(default=False, verbose_name='Is Data Import Completed')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
