# Generated by Django 4.0.4 on 2022-06-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        ('bulk_templates', '0003_alter_bulkupload_template_alter_template_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkupload',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='nodes.node', verbose_name='Node'),
        ),
    ]
