# Generated by Django 4.0.4 on 2022-06-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_alter_connection_source_alter_connection_supplychain_and_more'),
        ('tenants', '0015_alter_province_country_alter_tenantadmin_tenant_and_more'),
        ('bulk_templates', '0004_alter_bulkupload_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkupload',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='nodes.node', verbose_name='Node'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_templates', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
