# Generated by Django 4.0.4 on 2022-06-22 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0009_alter_templatefieldtype_data_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='width',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Width of cell'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='width',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Width of cell'),
        ),
        migrations.AlterField(
            model_name='templatefieldtype',
            name='data_generator',
            field=models.IntegerField(blank=True, choices=[(101, 'Countries'), (201, 'Provinces'), (301, 'Producers'), (401, 'Products'), (501, 'Operations'), (601, 'Currencies')], default=None, null=True, verbose_name='Data Generator'),
        ),
    ]
