# Generated by Django 4.0.4 on 2022-06-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0011_alter_templatefield_column_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='sheet_name',
            field=models.CharField(default='Data', max_length=100, verbose_name='Sheet Name'),
        ),
    ]
