# Generated by Django 4.0.4 on 2022-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0012_template_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Excel Description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='data_row',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Data Row Starting'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_row',
            field=models.IntegerField(blank=True, default=4, null=True, verbose_name='Title Row Starting'),
        ),
    ]
