# Generated by Django 4.0.4 on 2022-07-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0014_alter_template_options_template_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkupload',
            name='actors_added',
        ),
        migrations.RemoveField(
            model_name='bulkupload',
            name='actors_to_add',
        ),
        migrations.RemoveField(
            model_name='bulkupload',
            name='actors_to_update',
        ),
        migrations.RemoveField(
            model_name='bulkupload',
            name='actors_updated',
        ),
        migrations.RemoveField(
            model_name='bulkupload',
            name='transactions_added',
        ),
        migrations.RemoveField(
            model_name='bulkupload',
            name='transactions_to_add',
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='new_items_completed',
            field=models.IntegerField(default=0, verbose_name='New Items Completed'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='total_new_items',
            field=models.IntegerField(default=0, verbose_name='New Items'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='total_updations',
            field=models.IntegerField(default=0, verbose_name='Total Updations'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='updations_completed',
            field=models.IntegerField(default=0, verbose_name='Updations Completed'),
        ),
        migrations.AlterField(
            model_name='templatefieldtype',
            name='type',
            field=models.IntegerField(choices=[(101, 'String'), (111, 'Integer'), (121, 'Float'), (131, 'Date'), (141, 'Phone'), (151, 'Email')], default=101, verbose_name='Field Type'),
        ),
    ]
