# Generated by Django 4.0.4 on 2022-07-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0017_bulkupload_supply_chain_bulkupload_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupload',
            name='status',
            field=models.IntegerField(choices=[(101, 'Created'), (201, 'Validated'), (301, 'Initiated'), (401, 'In Progress'), (501, 'Completed')], default=101, verbose_name='Status'),
        ),
    ]
