# Generated by Django 4.0.4 on 2022-07-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0018_bulkupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupload',
            name='validated_data',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Data'),
        ),
    ]
