# Generated by Django 4.0.4 on 2022-07-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0019_bulkupload_validated_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkupload',
            name='status',
            field=models.IntegerField(choices=[(101, 'Created'), (201, 'Validated'), (301, 'Initiated'), (401, 'In Progress'), (501, 'Completed'), (601, 'Failed')], default=101, verbose_name='Status'),
        ),
    ]
