# Generated by Django 4.0.4 on 2022-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0020_alter_bulkupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefieldtype',
            name='data_generator',
            field=models.IntegerField(blank=True, choices=[(101, 'Countries'), (201, 'Provinces'), (301, 'Producers'), (401, 'Products'), (501, 'Operations'), (601, 'Currencies'), (701, 'Units')], default=None, null=True, verbose_name='Data Generator'),
        ),
    ]
