# Generated by Django 4.0.4 on 2022-07-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0021_alter_templatefieldtype_data_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='index_column',
            field=models.CharField(default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='templatefieldtype',
            name='type',
            field=models.IntegerField(choices=[(51, 'String'), (101, 'String'), (111, 'Integer'), (121, 'Float'), (131, 'Date'), (141, 'Phone'), (151, 'Email')], default=101, verbose_name='Field Type'),
        ),
    ]
