# Generated by Django 4.0.4 on 2022-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0023_alter_templatefieldtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkupload',
            name='validated_data',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Validated Data'),
        ),
    ]
