# Generated by Django 4.0.4 on 2022-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0024_alter_bulkupload_validated_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupload',
            name='new_items_failed',
            field=models.IntegerField(default=0, verbose_name='New Items Failed'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='updations_failed',
            field=models.IntegerField(default=0, verbose_name='Updations Failed'),
        ),
    ]
