# Generated by Django 4.0.4 on 2022-08-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0027_alter_template_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefieldtype',
            name='type',
            field=models.IntegerField(choices=[(51, 'Primary Key'), (101, 'String'), (111, 'Integer'), (115, 'Positive Integer'), (121, 'Float'), (125, 'Positive Float'), (131, 'Date'), (141, 'Phone'), (151, 'Email')], default=101, verbose_name='Field Type'),
        ),
    ]
