# Generated by Django 4.0.4 on 2022-08-12 10:54

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0028_alter_templatefieldtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description_en_uk',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Excel Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='description_en_us',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Excel Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Excel Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='description_nl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Excel Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_en_uk',
            field=models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_en_us',
            field=models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_fr',
            field=models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_name_en_uk',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template File Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_name_en_us',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template File Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template File Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template File Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='file_nl',
            field=models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Template Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='sheet_name_en_uk',
            field=models.CharField(default='Data', max_length=100, null=True, verbose_name='Sheet Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='sheet_name_en_us',
            field=models.CharField(default='Data', max_length=100, null=True, verbose_name='Sheet Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='sheet_name_fr',
            field=models.CharField(default='Data', max_length=100, null=True, verbose_name='Sheet Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='sheet_name_nl',
            field=models.CharField(default='Data', max_length=100, null=True, verbose_name='Sheet Name'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='description_en_uk',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description About Field'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='description_en_us',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description About Field'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description About Field'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='description_nl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description About Field'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='name_en_uk',
            field=models.CharField(max_length=500, null=True, verbose_name='Name Of Field'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='name_en_us',
            field=models.CharField(max_length=500, null=True, verbose_name='Name Of Field'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='name_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Name Of Field'),
        ),
        migrations.AddField(
            model_name='templatefieldtype',
            name='name_nl',
            field=models.CharField(max_length=500, null=True, verbose_name='Name Of Field'),
        ),
    ]
