# Generated by Django 4.0.4 on 2022-11-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0031_templatefield_can_read_templatefield_can_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefieldtype',
            name='placeholder',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
