# Generated by Django 4.0.4 on 2022-11-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0032_templatefieldtype_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set(),
        ),
    ]
