# Generated by Django 4.0.4 on 2023-11-08 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_templates', '0034_templatefieldtype_is_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.IntegerField(choices=[(101, 'Transaction'), (111, 'Connection'), (121, 'Questionnaire')], default=101, verbose_name='Template Type'),
        ),
        migrations.AlterField(
            model_name='templatefieldtype',
            name='template_type',
            field=models.IntegerField(choices=[(101, 'Transaction'), (111, 'Connection'), (121, 'Questionnaire')], default=101, verbose_name='Template Type'),
        ),
        migrations.AlterField(
            model_name='templatefieldtype',
            name='width',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Width of cell'),
        ),
    ]
