# Generated by Django 4.0.4 on 2022-05-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_batch_node'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackertheme',
            name='supply_chains',
            field=models.ManyToManyField(blank=True, related_name='themes', to='products.supplychain', verbose_name='Supplychains'),
        ),
    ]
