# Generated by Django 4.0.4 on 2022-05-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_unit_tenant'),
        ('dashboard', '0002_alter_trackertheme_supply_chains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackertheme',
            name='supply_chains',
            field=models.ManyToManyField(blank=True, related_name='tracker_themes', to='products.supplychain', verbose_name='Supplychains'),
        ),
    ]
