# Generated by Django 4.0.4 on 2022-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_trackertheme_supply_chains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardtheme',
            old_name='default',
            new_name='is_default',
        ),
        migrations.RenameField(
            model_name='trackertheme',
            old_name='default',
            new_name='is_default',
        ),
    ]
