# Generated by Django 4.0.4 on 2022-07-07 15:27

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_default_dashboardtheme_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_background',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Background Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_border_alpha',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Boarder Colour Aplpha'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_border_beta',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Boarder Colour Beta'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_font_alpha',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Font Colour Aplpha'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_font_beta',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Font Colour Beta'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_font_negative',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Font Colour Negative'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_primary_alpha',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Primary Colour Aplpha'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_primary_beta',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Primary Colour Beta'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_primary_delta',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Primary Colour Delta'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_primary_gamma',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Primary Colour Gamma'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_secondary',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Secondary Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_sidebar',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Sidebar Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=common.library._get_file_path),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='action_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Action Colour'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='colour_map_background',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Map Background Colour'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='colour_map_clustor',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Map Cluster Colour'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='colour_map_marker',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Map Marker Colour'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='colour_map_marker_text',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Map Marker Text Colour'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='colour_map_selected',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Selected Colour In Map'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='primary_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Primary Colour'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='primary_colour_light',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Primary Colour Light'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='secondary_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Secondary Colour'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='text_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Text Colour'),
        ),
    ]
