# Generated by Django 4.0.4 on 2022-07-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_alter_category_options'),
        ('dashboard', '0006_dashboardtheme_colour_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackertheme',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_themes', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
