# Generated by Django 4.0.4 on 2022-08-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_remove_tenant_transaction_form_and_more'),
        ('dashboard', '0007_alter_trackertheme_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtheme',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_theme', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
