# Generated by Django 4.0.4 on 2022-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_dashboardtheme_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtheme',
            name='danger_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Danger Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='success_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Success Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='warning_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Warning Colour'),
        ),
    ]
