# Generated by Django 4.0.4 on 2022-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dashboardtheme_danger_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardtheme',
            name='colour_background',
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='approved_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Approved Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_background_alpha',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Background Colour Alpha'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='colour_background_beta',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Background Colour Beta'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='error_text_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Error Text Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='pending_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Pending Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='placeholder_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Placeholder Colour'),
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='rejected_color',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Rejected Colour'),
        ),
    ]
