# Generated by Django 4.0.4 on 2022-09-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_batch_name_en_uk_batch_name_en_us_batch_name_fr_and_more'),
        ('nodes', '0028_node_upload_timestamp'),
        ('dashboard', '0010_remove_dashboardtheme_colour_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackertheme',
            name='batch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_theme', to='products.batch', verbose_name='Default Batch'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Theme Name'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_theme', to='nodes.node', verbose_name='Node'),
        ),
    ]
