# Generated by Django 4.0.4 on 2022-09-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_country_language'),
        ('dashboard', '0011_trackertheme_batch_trackertheme_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackertheme',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='trackertheme',
            unique_together={('tenant', 'name')},
        ),
    ]
