# Generated by Django 4.0.4 on 2022-09-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_trackertheme_action_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackertheme',
            name='primary_white',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Primary White'),
        ),
    ]
