# Generated by Django 4.0.4 on 2022-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_trackertheme_primary_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackertheme',
            name='header_boarder_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Border Colour Of Header'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='map_text_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Text Colour In Map'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='txn_type_colour_alpha',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Transaction Type Colour Alpha'),
        ),
        migrations.AddField(
            model_name='trackertheme',
            name='txn_type_colour_beta',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Transaction Type Colour Beta'),
        ),
    ]
