# Generated by Django 4.0.4 on 2023-09-29 10:10

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0049_country_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='SupplyChain Info Title')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionTenantRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('section_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('section_type', models.ForeignKey(limit_choices_to={'model__in': ['header', 'overviewsection', 'infosection', 'mapsection', 'supplychainsection', 'aboutsection', 'moreinfosection', 'footer']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_types', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci_theme_sections', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverViewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Overview Image')),
                ('title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Overview Title')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Site Link')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoreInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='MoreInfo Image')),
                ('subtitle', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Moreinfo SubTitle')),
                ('title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Moreinfo Title')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Moreinfo Description')),
                ('card1_image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='First Card Image')),
                ('card1_title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='First Card Title')),
                ('card1_file', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='First Card File')),
                ('card2_image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Second Card Image')),
                ('card2_title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Second Card Title')),
                ('card2_file', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Second Card File')),
                ('card3_image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Third Card Image')),
                ('card3_title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Third Card Title')),
                ('card3_file', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Third Card File')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='InfoView Image')),
                ('subtitle', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='InfoView SubTitle')),
                ('title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='InfoView Title')),
                ('subheading', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='InfoView SubHeading')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('logo', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='CI Logo')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('logo', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='CI Logo')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Section Name')),
                ('key', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Section Key')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Section Position')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Section')),
                ('image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='About Image')),
                ('title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='About Title')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='About Description')),
                ('website_link', models.URLField(blank=True, default=None, null=True, verbose_name='About Wbesite')),
                ('website_link_text', models.CharField(blank=True, default=None, max_length=5000, null=True, verbose_name='About Wbesite Button Text')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
