# Generated by Django 4.0.4 on 2023-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_interface', '0002_citheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='citheme',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Is Current Theme'),
        ),
    ]
