# Generated by Django 4.0.4 on 2023-09-29 10:53

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer_interface', '0003_citheme_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card1_file',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card1_image',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card1_title',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card2_file',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card2_image',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card2_title',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card3_file',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card3_image',
        ),
        migrations.RemoveField(
            model_name='moreinfosection',
            name='card3_title',
        ),
        migrations.CreateModel(
            name='CICard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Card Image')),
                ('title', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Card Title')),
                ('file', models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Card File')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Card Position')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='moreinfosection',
            name='cards',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='consumer_interface.cicard'),
        ),
    ]
