# Generated by Django 4.0.4 on 2023-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_interface', '0004_remove_moreinfosection_card1_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfosection',
            name='cards',
            field=models.ManyToManyField(blank=True, default=None, related_name='more_infos', to='consumer_interface.cicard'),
        ),
    ]
