# Generated by Django 4.0.4 on 2023-09-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0049_country_score'),
        ('consumer_interface', '0005_alter_moreinfosection_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontenantregister',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci_theme_sections', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
