# Generated by Django 4.0.4 on 2022-05-18 07:50

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0005_alter_connection_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='city',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Contact Person Name'),
        ),
        migrations.AddField(
            model_name='node',
            name='country',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='house_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='province',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='registration_no',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Node Registartion Number'),
        ),
        migrations.AddField(
            model_name='node',
            name='street',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='sub_province',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('node_type', models.IntegerField(choices=[(101, 'Company'), (111, 'Farmer')], default=101)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to=common.library._get_file_path)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='operations',
            field=models.ManyToManyField(blank=True, default=None, related_name='nodes', to='supply_chains.operation'),
        ),
    ]
