# Generated by Django 4.0.4 on 2022-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0009_remove_node_contact_name_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Contact Person Name'),
        ),
    ]
