# Generated by Django 4.0.4 on 2022-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0010_node_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedocument',
            name='type',
            field=models.IntegerField(choices=[(101, 'Company Document')], default=101, verbose_name='Document Type'),
        ),
    ]
