# Generated by Django 4.0.4 on 2022-05-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0011_nodedocument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemember',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='supply_chains.node', verbose_name='Node'),
        ),
    ]
