# Generated by Django 4.0.4 on 2022-05-25 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0012_alter_nodemember_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='Member User'),
        ),
    ]
