# Generated by Django 4.0.4 on 2022-06-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_default_node'),
        ('dynamic_forms', '0005_alter_formsubmission_node'),
        ('transactions', '0007_alter_externaltransaction_destination_and_more'),
        ('products', '0004_alter_batch_node'),
        ('claims', '0023_alter_attachedclaim_attached_by_and_more'),
        ('bulk_templates', '0004_alter_bulkupload_node'),
        ('supply_chains', '0013_alter_nodemember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='form',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='source_tags',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='supplychain',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='target',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='target_tags',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='node',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='node',
            name='form',
        ),
        migrations.RemoveField(
            model_name='node',
            name='operations',
        ),
        migrations.RemoveField(
            model_name='node',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='node',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='nodedocument',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='nodedocument',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodedocument',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='nodemember',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='nodemember',
            name='form',
        ),
        migrations.RemoveField(
            model_name='nodemember',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodemember',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='nodemember',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='nodemember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='NodeDocument',
        ),
        migrations.DeleteModel(
            name='NodeMember',
        ),
    ]
