# Generated by Django 4.0.4 on 2022-06-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_delete_connection'),
        ('tenants', '0015_alter_province_country_alter_tenantadmin_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0017_alter_operation_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('graph_id', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='GraphDB Id')),
                ('status', models.IntegerField(choices=[(101, 'Active'), (111, 'Inactive'), (121, 'Blocked')], default=111, verbose_name='Connection Status')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='nodes.node', verbose_name='Connected From')),
                ('source_tags', models.ManyToManyField(related_name='source_connections', to='supply_chains.tag', verbose_name='Source Node Tags')),
                ('supplychain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='supply_chains.supplychain', verbose_name='Supplychain')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_connections', to='nodes.node', verbose_name='Connected To')),
                ('target_tags', models.ManyToManyField(related_name='target_connections', to='supply_chains.tag', verbose_name='Source Node Tags')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
