# Generated by Django 4.0.4 on 2022-06-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_delete_connection'),
        ('supply_chains', '0018_connection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={},
        ),
        migrations.AlterField(
            model_name='connection',
            name='target_tags',
            field=models.ManyToManyField(related_name='target_connections', to='supply_chains.tag', verbose_name='Target Node Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('source', 'target', 'supplychain')},
        ),
    ]
