# Generated by Django 4.0.4 on 2022-06-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_alter_province_country_alter_tenantadmin_tenant_and_more'),
        ('nodes', '0009_delete_connection'),
        ('supply_chains', '0019_alter_connection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='nodes.node', verbose_name='Connected From'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='supplychain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='supply_chains.supplychain', verbose_name='Supplychain'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_connections', to='nodes.node', verbose_name='Connected To'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_operations', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='supplychain',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='Supplychain'),
        ),
        migrations.AlterField(
            model_name='supplychain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chains', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Tag'),
        ),
    ]
