# Generated by Django 4.0.4 on 2022-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0020_alter_connection_source_alter_connection_supplychain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='form',
            new_name='submission_form',
        ),
    ]
