# Generated by Django 4.0.4 on 2022-06-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0021_rename_form_connection_submission_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='number',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
