# Generated by Django 4.0.4 on 2022-06-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0022_connection_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='source_tags',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='target_tags',
        ),
        migrations.AddField(
            model_name='connection',
            name='connection_pair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paired_connections', to='supply_chains.connection', verbose_name='Connection pair'),
        ),
        migrations.AddField(
            model_name='connection',
            name='tags',
            field=models.ManyToManyField(related_name='connections', to='supply_chains.tag', verbose_name='Connection Tags'),
        ),
    ]
