# Generated by Django 4.0.4 on 2022-06-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0024_alter_connection_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Revoked')], default=101, verbose_name='Connection Status'),
        ),
    ]
