# Generated by Django 4.0.4 on 2022-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0025_alter_connection_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplychain',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='blocked',
            new_name='is_blocked',
        ),
    ]
