# Generated by Django 4.0.4 on 2022-06-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0018_alter_nodemember_is_active'),
        ('supply_chains', '0026_rename_active_supplychain_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='supplychain',
            new_name='supply_chain',
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('source', 'target', 'supply_chain')},
        ),
    ]
