# Generated by Django 4.0.4 on 2022-06-29 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0020_alter_nodemember_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0027_rename_supplychain_connection_supply_chain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSupplyChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_chains', to='nodes.node', verbose_name='Node')),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='supply_chains.supplychain', verbose_name='Supply Chain')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
