# Generated by Django 4.0.4 on 2022-06-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0028_nodesupplychain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesupplychain',
            name='supply_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_supplychains', to='supply_chains.supplychain', verbose_name='Supply Chain'),
        ),
    ]
