# Generated by Django 4.0.4 on 2022-07-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0030_alter_nodesupplychain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychain',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='Supply Chain Name'),
        ),
    ]
