# Generated by Django 4.0.4 on 2022-11-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0028_node_upload_timestamp'),
        ('supply_chains', '0032_operation_name_en_uk_operation_name_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to='nodes.node', verbose_name='Invited By'),
        ),
    ]
