# Generated by Django 4.0.4 on 2022-12-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0032_operation_name_en_uk_operation_name_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='in_dashboard',
            field=models.BooleanField(default=True, verbose_name='Dashboard_visible'),
        ),
        migrations.AddField(
            model_name='operation',
            name='in_forms',
            field=models.BooleanField(default=True, verbose_name='Form_visible'),
        ),
    ]
