# Generated by Django 4.0.4 on 2023-01-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0033_operation_in_dashboard_operation_in_forms'),
        ('supply_chains', '0034_auto_20221109_0556'),
    ]

    operations = [
    ]
