# Generated by Django 4.0.4 on 2023-01-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0033_operation_in_dashboard_operation_in_forms'),
        ('supply_chains', '0035_operation_invitation_form_operation_signup_form'),
    ]

    operations = [
    ]
