# Generated by Django 4.0.4 on 2023-01-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0035_merge_20230103_0914'),
        ('supply_chains', '0036_merge_20230103_0749'),
    ]

    operations = [
    ]
