# Generated by Django 4.0.4 on 2023-01-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0037_merge_20230103_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='initiation',
            field=models.IntegerField(choices=[(101, 'Manual'), (201, 'System')], default=101),
        ),
    ]
