# Generated by Django 4.0.4 on 2023-01-03 21:24

from django.db import migrations


def update_connection_initiation(apps, schema_editor):
    """
    Function populate currency model with currency data.
    """
    from v1.supply_chains.constants import ConnectionInitiation
    Connection = apps.get_model('supply_chains', 'Connection')

    for connection in Connection.objects.all():
        if connection.target == connection.invited_by:
            connection.initiation = ConnectionInitiation.SYSTEM
            connection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0038_connection_initiation'),
    ]

    operations = [
        migrations.RunPython(update_connection_initiation),
    ]
