# Generated by Django 4.0.4 on 2023-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0039_connection_symmetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_buyer',
            field=models.BooleanField(default=True, verbose_name='Target is a Buyer'),
        ),
        migrations.AddField(
            model_name='connection',
            name='is_supplier',
            field=models.BooleanField(default=True, verbose_name='Target is a Supplier'),
        ),
    ]
