# Generated by Django 4.0.4 on 2023-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0041_alter_connection_submission_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='submission_form_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Extra Form Data Mongo Submission Id'),
        ),
    ]
