# Generated by Django 4.0.4 on 2023-07-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0043_alter_nodesupplychain_node_alter_tag_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesupplychain',
            name='sc_risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
