# Generated by Django 4.0.4 on 2023-09-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0043_alter_nodesupplychain_node_alter_tag_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Operation Position'),
        ),
    ]
