# Generated by Django 4.0.4 on 2023-08-08 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0044_nodesupplychain_sc_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesupplychain',
            name='sc_risk_updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
