# Generated by Django 4.0.4 on 2023-09-18 06:54

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0044_operation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='position',
            field=positions.fields.PositionField(default=1, verbose_name='Operation Position'),
        ),
    ]
