# Generated by Django 4.0.4 on 2023-09-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0045_alter_operation_position'),
        ('supply_chains', '0045_nodesupplychain_sc_risk_updated_on'),
    ]

    operations = [
    ]
