# Generated by Django 4.0.4 on 2022-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_alter_claim_reference_alter_criterion_reference'),
        ('transactions', '0003_alter_transaction_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionenquiry',
            name='claims',
        ),
        migrations.AddField(
            model_name='transactionenquiry',
            name='claims',
            field=models.ManyToManyField(related_name='transaction_enquiries', to='claims.claim', verbose_name='Claims Needed'),
        ),
    ]
