# Generated by Django 4.0.4 on 2022-05-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transactionenquiry_claims_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(101, 'Transaction Created'), (111, 'Transaction Declined'), (121, 'Transaction On-hold'), (131, 'Transaction  Approved')], default=101, verbose_name='Status Of Transaction'),
        ),
    ]
