# Generated by Django 4.0.4 on 2022-06-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        ('transactions', '0006_alter_transaction_form_alter_transaction_parents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransaction',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='nodes.node', verbose_name='Destination Node'),
        ),
        migrations.AlterField(
            model_name='externaltransaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='nodes.node', verbose_name='Source Node'),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internaltransactions', to='nodes.node', verbose_name='Node'),
        ),
        migrations.AlterField(
            model_name='transactionenquiry',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_enquiries', to='nodes.node', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='transactionenquiry',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_enquiries', to='nodes.node', verbose_name='Sender'),
        ),
    ]
