# Generated by Django 4.0.4 on 2022-06-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_alter_connection_source_alter_connection_supplychain_and_more'),
        ('products', '0006_alter_batch_product_alter_batch_tenant_and_more'),
        ('transactions', '0007_alter_externaltransaction_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransaction',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='nodes.node', verbose_name='Destination Node'),
        ),
        migrations.AlterField(
            model_name='externaltransaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='nodes.node', verbose_name='Source Node'),
        ),
        migrations.AlterField(
            model_name='sourcebatch',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transaction_objects', to='products.batch', verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='sourcebatch',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_batch_objects', to='transactions.transaction', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='transactionenquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_enquiries', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='transactionenquiry',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_enquiries', to='nodes.node', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='transactionenquiry',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_enquiries', to='nodes.node', verbose_name='Sender'),
        ),
    ]
