# Generated by Django 4.0.4 on 2022-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_externaltransaction_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='form',
            new_name='submission_form',
        ),
        migrations.RenameField(
            model_name='transactionenquiry',
            old_name='form',
            new_name='submission_form',
        ),
    ]
