# Generated by Django 4.0.4 on 2022-06-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_active_product_is_active_and_more'),
        ('transactions', '0011_alter_transaction_result_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcebatch',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Quantity In KG'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=25, null=True, verbose_name='Destination Product Quantity In KG'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=25, null=True, verbose_name='Source Product Quantity In KG'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='transactionenquiry',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Qunatity Of Product In KG'),
        ),
    ]
