# Generated by Django 4.0.4 on 2022-06-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_sourcebatch_quantity_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Note'),
        ),
    ]
