# Generated by Django 4.0.4 on 2022-06-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransaction',
            name='type',
            field=models.IntegerField(choices=[(101, 'Incoming'), (111, 'Outgoing'), (121, 'Reversal')], default=101, verbose_name='Type Of External Transaction'),
        ),
    ]
