# Generated by Django 4.0.4 on 2022-06-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_alter_currency_options_tenant_currencies'),
        ('transactions', '0014_alter_externaltransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_transactions', to='tenants.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='transactionenquiry',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txn_enquiries', to='tenants.currency', verbose_name='Currency'),
        ),
    ]
