# Generated by Django 4.0.4 on 2022-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_externaltransaction_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
