# Generated by Django 4.0.4 on 2022-06-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_transaction_result_batches'),
        ('transactions', '0017_transactioncomment'),
    ]

    operations = [
    ]
