# Generated by Django 4.0.4 on 2022-06-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_merge_20220623_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionenquiry',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='transactionenquiry',
            name='status',
            field=models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Rejected'), (131, 'On-hold'), (141, 'Cancelled')], default=101, verbose_name='Enquiry Status'),
        ),
    ]
