# Generated by Django 4.0.4 on 2022-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_transactionenquiry_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionenquiry',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
