# Generated by Django 4.0.4 on 2022-06-27 06:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0019_alter_currency_options_tenant_currencies'),
        ('nodes', '0019_node_trace_code'),
        ('products', '0011_batch_number'),
        ('claims', '0026_rename_active_claim_is_active_and_more'),
        ('dynamic_forms', '0016_alter_formfield_label_alter_formfield_place_holder_and_more'),
        ('transactions', '0020_transactionenquiry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Qunatity Of Product')),
                ('expected_date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Expected Delivery Date')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Qunatity Of Product')),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Qunatity Of Product In KG')),
                ('status', models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Rejected'), (131, 'On-hold'), (141, 'Cancelled')], default=101, verbose_name='Enquiry Status')),
                ('expected_date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Expected Delivery Date')),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Enquiry Date')),
                ('last_noti_date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Last Notification Date')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('claims', models.ManyToManyField(related_name='requested_enquiries', to='claims.claim', verbose_name='Claims Needed')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txn_enquiries', to='tenants.currency', verbose_name='Currency')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_enquiries', to='products.product', verbose_name='Product')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_enquiries', to='nodes.node', verbose_name='Receiver')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_enquiries', to='nodes.node', verbose_name='Sender')),
                ('submission_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_enquiry', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit', verbose_name='Unit Of Product')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TransactionEnquiry',
        ),
        migrations.AddField(
            model_name='deliverynotification',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notification', to='transactions.purchaseorder', verbose_name='PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='deliverynotification',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
