# Generated by Django 4.0.4 on 2022-06-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_transaction_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
