# Generated by Django 4.0.4 on 2022-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_alter_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=25, null=True, verbose_name='Destination Product Quantity In KG'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=25, null=True, verbose_name='Source Product Quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=25, null=True, verbose_name='Source Product Quantity In KG'),
        ),
    ]
