# Generated by Django 4.0.4 on 2022-07-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_tenant_block_chain_request_tenant_topic_id'),
        ('transactions', '0025_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
    ]
