# Generated by Django 4.0.4 on 2022-07-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_transaction_destination_quantity_kg_and_more'),
        ('transactions', '0026_transaction_tenant'),
    ]

    operations = [
    ]
