# Generated by Django 4.0.4 on 2022-07-18 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_merge_20220718_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Transaction Date'),
        ),
    ]
