# Generated by Django 4.0.4 on 2022-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Rejected'), (131, 'On-hold'), (141, 'Cancelled'), (151, 'Partial')], default=101, verbose_name='PurachaseOrder Status'),
        ),
    ]
