# Generated by Django 4.0.4 on 2022-07-19 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='expected_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Enquiry Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Expected Delivery Date'),
        ),
    ]
