# Generated by Django 4.0.4 on 2022-07-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_purchaseorder_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remaining_quantity_kg',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Sent Quantity Of Product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_quantity_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Sent Quantity Of Product In KG'),
        ),
    ]
