# Generated by Django 4.0.4 on 2022-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_remove_purchaseorder_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Rejection Reason'),
        ),
    ]
