# Generated by Django 4.0.4 on 2022-07-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_purchaseorder_rejection_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Quantity Of Product'),
        ),
    ]
