# Generated by Django 4.0.4 on 2022-08-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0025_alter_node_city_alter_node_description_and_more'),
        ('transactions', '0036_alter_externaltransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncomment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txn_comments', to='nodes.nodemember', verbose_name='Commenter'),
        ),
    ]
