# Generated by Django 4.0.4 on 2022-08-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_transaction_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
