# Generated by Django 4.0.4 on 2022-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_transaction_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransaction',
            name='upload_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Upload Id'),
        ),
    ]
