# Generated by Django 4.0.4 on 2022-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_externaltransaction_upload_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaltransaction',
            name='upload_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='upload_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Upload Id'),
        ),
    ]
