# Generated by Django 4.0.4 on 2022-09-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_remove_externaltransaction_upload_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='upload_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='upload_timestamp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Upload Id'),
        ),
    ]
