# Generated by Django 4.0.4 on 2022-09-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_remove_transaction_upload_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rejection_reason',
            field=models.IntegerField(choices=[(101, 'Quality Issue'), (111, 'Data Issue'), (121, 'Other Reason')], default=121, verbose_name='Transaction Rejection Reason'),
        ),
    ]
