# Generated by Django 4.0.4 on 2022-09-15 08:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_alter_transaction_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rejection_reason',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Transaction Rejection Reason'),
        ),
    ]
