# Generated by Django 4.0.4 on 2023-04-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0023_form_description_form_name'),
        ('transactions', '0048_alter_transactioncomment_company_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='submission_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_enquiry', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submission_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data'),
        ),
    ]
