# Generated by Django 4.0.4 on 2023-07-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0036_alter_node_tenant_alter_nodedocument_file_and_more'),
        ('products', '0021_alter_batch_node_alter_batch_product_and_more'),
        ('transactions', '0050_purchaseorder_submission_form_mongo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotification',
            name='purchase_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notification', to='transactions.purchaseorder', verbose_name='PurchaseOrder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externaltransaction',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='nodes.node', verbose_name='Destination Node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='internaltransactions', to='nodes.node', verbose_name='Node'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_enquiries', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_enquiries', to='nodes.node', verbose_name='Receiver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_enquiries', to='nodes.node', verbose_name='Sender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcebatch',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transaction_objects', to='products.batch', verbose_name='Batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactioncomment',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='transactions.transaction', verbose_name='Transaction'),
            preserve_default=False,
        ),
    ]
