# Generated by Django 4.0.4 on 2022-05-16 19:09

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenantadmin_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Rejected'), (131, 'Partial'), (141, 'On Hold')], default=101, verbose_name='Claim Current Status')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttachedCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Rejected'), (131, 'Partial'), (141, 'On Hold')], default=101, verbose_name='Current Status')),
            ],
            options={
                'verbose_name_plural': 'Attached criteria',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=500, verbose_name='Claim')),
                ('description', models.CharField(blank=True, default='', max_length=2000, verbose_name='Description')),
                ('type', models.IntegerField(choices=[(101, 'Product Claim'), (111, 'Company Claim')], default=101, verbose_name='Claim Type')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=common.library._get_file_path, verbose_name='Photo')),
                ('proportional', models.BooleanField(default=True, verbose_name='Is Claim Proportional')),
                ('removable', models.BooleanField(default=False, verbose_name='Is Claim Removable')),
                ('inheritable', models.IntegerField(choices=[(1, 'Never Inherit'), (2, 'Always Inherit'), (3, 'Product Inheritance')], default=1, verbose_name='Claim Inheritance Type')),
                ('transaction_attachment', models.BooleanField(default=False, verbose_name='Can Attach With Transaction')),
                ('batch_attachment', models.BooleanField(default=False, verbose_name='Can Attach With Batch')),
                ('verification_type', models.IntegerField(choices=[(101, 'None'), (111, 'System'), (121, 'Second Party'), (131, 'Third Party')], default=101, verbose_name='Verification Type')),
                ('reference', models.CharField(default='jgGonZFfGIGYUCqF', max_length=16, verbose_name='Reference Number')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('supply_chains', models.ManyToManyField(blank=True, related_name='claims', to='products.supplychain', verbose_name='Supply Chains')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchClaim',
            fields=[
                ('attachedclaim_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.attachedclaim')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
            bases=('claims.attachedclaim',),
        ),
        migrations.CreateModel(
            name='BatchCriterion',
            fields=[
                ('attachedcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.attachedcriterion')),
            ],
            options={
                'verbose_name_plural': 'Attached batch criteria',
            },
            bases=('claims.attachedcriterion',),
        ),
        migrations.CreateModel(
            name='CompanyClaim',
            fields=[
                ('attachedclaim_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.attachedclaim')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
            bases=('claims.attachedclaim',),
        ),
        migrations.CreateModel(
            name='CompanyCriterion',
            fields=[
                ('attachedcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.attachedcriterion')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
            bases=('claims.attachedcriterion',),
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Claim Criterion')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Is Criterion Mandatory')),
                ('verification_type', models.IntegerField(choices=[(101, 'System'), (111, 'Second Party')], default=101, verbose_name='Verification Type')),
                ('reference', models.CharField(default='ISZpPJNLDfcbK1UR', max_length=16, verbose_name='Reference Number')),
                ('version', models.IntegerField(default=1, verbose_name='Version Of Criterion')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.claim', verbose_name='Claim')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Criteria',
            },
        ),
    ]
