# Generated by Django 4.0.4 on 2022-05-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='reference',
            field=models.CharField(default='QeRYwsriR0k2hz9i', max_length=16, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='reference',
            field=models.CharField(default='CNVt2xVsilTJnxXd', max_length=16, verbose_name='Reference Number'),
        ),
    ]
