# Generated by Django 4.0.4 on 2022-05-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_initial'),
        ('claims', '0006_alter_claim_reference_alter_criterion_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedcriterion',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_criterion', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='reference',
            field=models.CharField(default='NTN4s2u7iWv3vI7R', max_length=16, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='reference',
            field=models.CharField(default='aeFLdavSIjsXqnlh', max_length=16, verbose_name='Reference Number'),
        ),
    ]
