# Generated by Django 4.0.4 on 2022-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_attachedcriterion_form_alter_claim_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='reference',
            field=models.CharField(default='Pj6LFxE6tClrlW4h', max_length=16, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='reference',
            field=models.CharField(default='mnsk1BwtZYWrI2Z5', max_length=16, verbose_name='Reference Number'),
        ),
    ]
