# Generated by Django 4.0.4 on 2022-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_alter_claim_reference_alter_criterion_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='reference',
            field=models.CharField(default='BmV6noVD2FCDHF9T', max_length=16, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='reference',
            field=models.CharField(default='aXTVQptO4EBzxcX8', max_length=16, verbose_name='Reference Number'),
        ),
    ]
