# Generated by Django 4.0.4 on 2022-06-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_externaltransaction_destination_and_more'),
        ('products', '0006_alter_batch_product_alter_batch_tenant_and_more'),
        ('tenants', '0015_alter_province_country_alter_tenantadmin_tenant_and_more'),
        ('claims', '0023_alter_attachedclaim_attached_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedclaim',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_claims', to='claims.claim', verbose_name='Attached Claim'),
        ),
        migrations.AlterField(
            model_name='attachedcriterion',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_criteria', to='claims.criterion', verbose_name='Criterion'),
        ),
        migrations.AlterField(
            model_name='batchclaim',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_claims', to='products.batch', verbose_name='Claim Attached Batch'),
        ),
        migrations.AlterField(
            model_name='batchclaim',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_claims', to='transactions.transaction', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='batchcriterion',
            name='batch_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.batchclaim', verbose_name='Criterion Attached Batch Claim'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='companycriterion',
            name='company_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.companyclaim', verbose_name='Criterion Attached Company Claim'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.claim', verbose_name='Claim'),
        ),
    ]
