# Generated by Django 4.0.4 on 2022-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0025_alter_claim_supply_chains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='batch_attachment',
            new_name='is_batch_attachment',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='proportional',
            new_name='is_proportional',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='removable',
            new_name='is_removable',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='transaction_attachment',
            new_name='is_transaction_attachment',
        ),
    ]
