# Generated by Django 4.0.4 on 2022-06-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0016_alter_formfield_label_alter_formfield_place_holder_and_more'),
        ('claims', '0026_rename_active_claim_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedcriterion',
            old_name='form',
            new_name='form_submission',
        ),
        migrations.AddField(
            model_name='criterion',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attatchec_criterion', to='dynamic_forms.form', verbose_name='Fields'),
        ),
    ]
