# Generated by Django 4.0.4 on 2022-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0027_rename_form_attachedcriterion_form_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchclaim',
            name='verification_percentage',
            field=models.FloatField(default=0),
        ),
    ]
