# Generated by Django 4.0.4 on 2022-06-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0028_batchclaim_verification_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedclaim',
            name='attached_type',
            field=models.IntegerField(choices=[(101, 'Manual'), (111, 'Inheritance')], default=101, verbose_name='Attachment Type'),
        ),
        migrations.AddField(
            model_name='attachedcriterion',
            name='attached_type',
            field=models.IntegerField(choices=[(101, 'Manual'), (111, 'Inheritance')], default=101, verbose_name='Attachment Type'),
        ),
    ]
