# Generated by Django 4.0.4 on 2022-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0029_attachedclaim_attached_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='inheritable',
            field=models.IntegerField(choices=[(101, 'Never Inherit'), (111, 'Always Inherit'), (121, 'Product Inheritance')], default=101, verbose_name='Claim Inheritance Type'),
        ),
    ]
