# Generated by Django 4.0.4 on 2022-07-15 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('claims', '0030_alter_claim_inheritable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedclaim',
            name='message_hash',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='attachedclaim',
            name='message_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='attachedclaim',
            name='submit_message_request',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_msg_req', to='blockchain.blockchainrequest'),
        ),
    ]
