# Generated by Django 4.0.4 on 2022-08-09 00:28

from django.db import migrations


def change_claim_data(apps, schema_editor):
    Claim = apps.get_model('claims', 'Claim')
    AttachedClaim = apps.get_model('claims', 'AttachedClaim')
    for ac in AttachedClaim.objects.all():
        ac.attached_to = ac.claim.type
        ac.save()
    for c in Claim.objects.all():
        if c.type == 101:
            c.attach_to_node = False
            c.attach_from_profile = False
            c.attach_while_connecting = False
            c.attach_to_batch = True
            c.attach_from_batch_details = True
            c.attach_while_transacting = True
        else:
            c.attach_to_node = True
            c.attach_from_profile = True
            c.attach_while_connecting = False
            c.attach_to_batch = False
            c.attach_from_batch_details = False
            c.attach_while_transacting = False
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0033_rename_attached_type_attachedcriterion_attached_via_and_more'),
    ]

    operations = [
        migrations.RunPython(change_claim_data)
    ]
