# Generated by Django 4.0.4 on 2022-08-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0025_alter_node_city_alter_node_description_and_more'),
        ('claims', '0034_claim_changes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyClaim',
            new_name='NodeClaim',
        ),
        migrations.RenameModel(
            old_name='CompanyCriterion',
            new_name='NodeCriterion',
        ),
    ]
