# Generated by Django 4.0.4 on 2022-08-09 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0025_alter_node_city_alter_node_description_and_more'),
        ('claims', '0035_nodeclaim_remove_nodecriterion_company_claim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodecriterion',
            old_name='company_claim',
            new_name='node_claim',
        ),
        migrations.AlterField(
            model_name='attachedclaim',
            name='attached_to',
            field=models.IntegerField(choices=[(101, 'Batch'), (111, 'Node')], default=101, verbose_name='Claim Attached to'),
        ),
        migrations.AlterField(
            model_name='attachedcriterion',
            name='attached_via',
            field=models.IntegerField(choices=[(101, 'Manual'), (111, 'Inheritance')], default=101, verbose_name='Attached Via'),
        ),
        migrations.AlterField(
            model_name='nodeclaim',
            name='node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_claims', to='nodes.node', verbose_name='Company'),
        ),
    ]
