# Generated by Django 4.0.4 on 2022-08-09 02:13

from django.db import migrations, models
import functools
import utilities.function_generators


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0036_rename_company_claim_nodecriterion_node_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='code',
            field=models.CharField(default=functools.partial(utilities.function_generators.formatter, *('{r10}',), **{}), max_length=100, verbose_name='Claim Code'),
        ),
    ]
