# Generated by Django 4.0.4 on 2022-08-09 02:14

from django.db import migrations, models
import functools
import utilities.function_generators


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0037_claim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='code',
            field=models.CharField(default=functools.partial(utilities.function_generators.formatter, *('{r10}',), **{}), max_length=100, unique=True, verbose_name='Claim Code'),
        ),
    ]
