# Generated by Django 4.0.4 on 2022-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0038_alter_claim_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='description_en_uk',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='claim',
            name='description_en_us',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='claim',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='claim',
            name='description_nl',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='claim',
            name='name_en_uk',
            field=models.CharField(max_length=500, null=True, verbose_name='Claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='name_en_us',
            field=models.CharField(max_length=500, null=True, verbose_name='Claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='name_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='name_nl',
            field=models.CharField(max_length=500, null=True, verbose_name='Claim'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='description_en_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='description_en_us',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='description_nl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Claim Criterion'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Claim Criterion'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Claim Criterion'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Claim Criterion'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='attach_to_batch',
            field=models.BooleanField(default=True, verbose_name='Can claim be attached to companies? (Formerly product claims)'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='attach_to_node',
            field=models.BooleanField(default=True, verbose_name='Can claim be attached to nodes? (Formerly company claims)'),
        ),
    ]
