# Generated by Django 4.0.4 on 2022-08-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0038_alter_claim_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='is_batch_attachment',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='is_transaction_attachment',
        ),
    ]
