# Generated by Django 4.0.4 on 2022-08-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0039_claim_description_en_uk_claim_description_en_us_and_more'),
        ('claims', '0039_remove_claim_is_batch_attachment_and_more'),
    ]

    operations = [
    ]
