# Generated by Django 4.0.4 on 2022-08-17 03:03

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0026_alter_node_trace_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0040_merge_20220809_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedClaimComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Document Name')),
                ('file', models.FileField(blank=True, default=None, max_length=500, null=True, upload_to=common.library._get_file_path, verbose_name='Document')),
                ('attached_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='claims.attachedclaim', verbose_name='Claim')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_comments', to='nodes.nodemember', verbose_name='Commenter')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
