# Generated by Django 4.0.4 on 2022-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0041_attachedclaimcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='attach_to_batch',
            field=models.BooleanField(default=True, verbose_name='Can claim be attached to batches? (Formerly product claims)'),
        ),
    ]
