# Generated by Django 4.0.4 on 2022-11-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0028_node_upload_timestamp'),
        ('claims', '0042_alter_claim_attach_to_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedclaimcomment',
            name='company_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_document', to='nodes.nodedocument'),
        ),
    ]
