# Generated by Django 4.0.4 on 2023-04-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0044_alter_attachedclaimcomment_company_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='reference',
        ),
        migrations.AddField(
            model_name='claim',
            name='standard_id',
            field=models.CharField(default='', help_text='ID of Standard received from Risk Analysis module', max_length=32, null=True, verbose_name='Standard ID'),
        ),
    ]
