# Generated by Django 4.0.4 on 2023-04-06 13:13

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0045_remove_claim_reference_claim_standard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedclaim',
            name='certification_date',
            field=models.DateField(blank=True, default=None, help_text='Date on which the item was certified.', null=True, verbose_name='Certification Date'),
        ),
        migrations.AddField(
            model_name='attachedclaim',
            name='certification_number',
            field=models.CharField(blank=True, default='', help_text='Reference number of the certification', max_length=200, null=True, verbose_name='Certification Number'),
        ),
        migrations.AddField(
            model_name='attachedclaim',
            name='certified_by',
            field=models.CharField(blank=True, default='', help_text='Name of the Certification body that has Issues/Approved the Claim', max_length=2000, null=True, verbose_name='Certification Body'),
        ),
        migrations.AddField(
            model_name='attachedclaim',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=common.library._get_file_path, verbose_name='Certificate Document'),
        ),
        migrations.AddField(
            model_name='attachedclaim',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, help_text='Date of expiry of the certification/claim', null=True, verbose_name='Expiry Date'),
        ),
    ]
