# Generated by Django 4.0.4 on 2023-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0046_attachedclaim_certification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedclaim',
            name='certification_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='added_by',
            field=models.IntegerField(choices=[(101, 'Tenant'), (111, 'RO_AI')], default=101, verbose_name='Claim Created By'),
        ),
    ]
