# Generated by Django 4.0.4 on 2023-04-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0047_attachedclaim_certification_id_claim_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedclaim',
            name='certification_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Certificate Id From RO-AI'),
        ),
    ]
