# Generated by Django 4.0.4 on 2023-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0048_alter_attachedclaim_certification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedclaim',
            name='status',
            field=models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Rejected'), (131, 'Partial'), (141, 'On Hold'), (151, 'Expired')], default=101, verbose_name='Claim Current Status'),
        ),
        migrations.AlterField(
            model_name='attachedcriterion',
            name='status',
            field=models.IntegerField(choices=[(101, 'Pending'), (111, 'Approved'), (121, 'Rejected'), (131, 'Partial'), (141, 'On Hold'), (151, 'Expired')], default=101, verbose_name='Current Status'),
        ),
    ]
