# Generated by Django 4.0.4 on 2023-04-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0049_alter_attachedclaim_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedclaim',
            name='attached_via',
            field=models.IntegerField(choices=[(101, 'Manual'), (111, 'Inheritance'), (121, 'Sync')], default=101, verbose_name='Attached Via'),
        ),
        migrations.AlterField(
            model_name='attachedcriterion',
            name='attached_via',
            field=models.IntegerField(choices=[(101, 'Manual'), (111, 'Inheritance'), (121, 'Sync')], default=101, verbose_name='Attached Via'),
        ),
    ]
