# Generated by Django 4.0.4 on 2023-04-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0023_form_description_form_name'),
        ('claims', '0050_alter_attachedclaim_attached_via_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedcriterion',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_criterion', to='dynamic_forms.formsubmission', verbose_name='Extra Form Data'),
        ),
    ]
