# Generated by Django 4.0.4 on 2023-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0042_connection_submission_form_mongo_id'),
        ('claims', '0051_alter_attachedcriterion_form_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('main_txn_type', models.IntegerField(blank=True, choices=[(101, 'External Transaction'), (111, 'Internal Transaction')], default=101, verbose_name='Main Transaction Type')),
                ('child_txn_type', models.IntegerField(blank=True, choices=[(101, 'Processing And Incoming'), (111, 'Outgoing And Loss'), (121, 'Merge And Reversal'), (131, 'Incoming Without Source')], default=None, unique=True, verbose_name='Child Transaction Type')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attachedcriterion',
            name='submission_form_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='MongoDB Form Submission Id'),
        ),
        migrations.AddField(
            model_name='claim',
            name='operations',
            field=models.ManyToManyField(blank=True, related_name='claims', to='supply_chains.operation', verbose_name='Node Operations'),
        ),
    ]
