# Generated by Django 4.0.4 on 2023-05-26 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_batch_batch_specific_form_and_more'),
        ('claims', '0052_claimtransactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='product_types',
            field=models.ManyToManyField(blank=True, related_name='claims', to='products.producttype', verbose_name='Product Types'),
        ),
        migrations.AddField(
            model_name='claim',
            name='verifier_can_edit',
            field=models.BooleanField(default=False, verbose_name='Verifier Can Edit Attached Evidence'),
        ),
        migrations.AddField(
            model_name='claimtransactiontype',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_types', to='claims.claim', verbose_name='Claim'),
        ),
        migrations.AddField(
            model_name='claimtransactiontype',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimtransactiontype',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
