# Generated by Django 4.0.4 on 2023-06-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0027_formfieldvalue_submission_form_mongo_id_and_more'),
        ('claims', '0053_claim_product_types_claim_verifier_can_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedcriterion',
            name='verifier_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier_criterion', to='dynamic_forms.formsubmission', verbose_name='Verifier Form Data'),
        ),
        migrations.AddField(
            model_name='attachedcriterion',
            name='verifier_submission_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='MongoDB Form Submission Id'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='verifier_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifer_criterion', to='dynamic_forms.form', verbose_name='Verifer Form'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attatched_criterion', to='dynamic_forms.form', verbose_name='Fields'),
        ),
    ]
