# Generated by Django 4.0.4 on 2023-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0044_tenant_product_grouping'),
        ('claims', '0054_attachedcriterion_verifier_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='claims', to='tenants.country', verbose_name='Countries'),
        ),
    ]
