# Generated by Django 4.0.4 on 2023-06-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0042_connection_submission_form_mongo_id'),
        ('claims', '0055_claim_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionClaim',
            fields=[
                ('attachedclaim_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.attachedclaim')),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_claims', to='supply_chains.connection', verbose_name='Connection')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
            bases=('claims.attachedclaim',),
        ),
        migrations.AlterField(
            model_name='attachedclaim',
            name='attached_to',
            field=models.IntegerField(choices=[(101, 'Batch'), (111, 'Node'), (121, 'Connection')], default=101, verbose_name='Claim Attached to'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.IntegerField(choices=[(101, 'Product Claim'), (111, 'Company Claim'), (121, 'Connection Claim')], default=101, verbose_name='Claim Type'),
        ),
        migrations.CreateModel(
            name='ConnectionCriterion',
            fields=[
                ('attachedcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.attachedcriterion')),
                ('connection_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.connectionclaim', verbose_name='Criterion Attached To Connection')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
            bases=('claims.attachedcriterion',),
        ),
    ]
