# Generated by Django 4.0.4 on 2023-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0057_claim_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimtransactiontype',
            options={},
        ),
        migrations.AlterField(
            model_name='claimtransactiontype',
            name='child_txn_type',
            field=models.IntegerField(blank=True, choices=[(101, 'Processing And Incoming'), (111, 'Outgoing And Loss'), (121, 'Merge And Reversal'), (131, 'Incoming Without Source')], default=None, verbose_name='Child Transaction Type'),
        ),
        migrations.AlterUniqueTogether(
            name='claimtransactiontype',
            unique_together={('claim', 'main_txn_type', 'child_txn_type')},
        ),
    ]
