# Generated by Django 4.0.4 on 2023-07-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0036_alter_node_tenant_alter_nodedocument_file_and_more'),
        ('supply_chains', '0043_alter_nodesupplychain_node_alter_tag_tenant'),
        ('products', '0021_alter_batch_node_alter_batch_product_and_more'),
        ('claims', '0058_alter_claimtransactiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedclaimcomment',
            name='attached_claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='claims.attachedclaim', verbose_name='Claim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachedcriterion',
            name='criterion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attached_criteria', to='claims.criterion', verbose_name='Criterion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchclaim',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batch_claims', to='products.batch', verbose_name='Claim Attached Batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchcriterion',
            name='batch_claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.batchclaim', verbose_name='Criterion Attached Batch Claim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionclaim',
            name='connection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='connection_claims', to='supply_chains.connection', verbose_name='Connection'),
        ),
        migrations.AlterField(
            model_name='connectioncriterion',
            name='connection_claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.connectionclaim', verbose_name='Criterion Attached To Connection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criterion',
            name='claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.claim', verbose_name='Claim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodeclaim',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='node_claims', to='nodes.node', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodecriterion',
            name='node_claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='claims.nodeclaim', verbose_name='Criterion Attached Company Claim'),
            preserve_default=False,
        ),
    ]
