# Generated by Django 4.0.4 on 2023-11-08 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_answer_is_deleted_alter_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.question', verbose_name='Question'),
        ),
    ]
