# Generated by Django 4.0.4 on 2023-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0052_auto_20231122_0722'),
        ('questionnaire', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='tags',
            field=models.ManyToManyField(related_name='questionnaires', to='tenants.tag', verbose_name='Questionnaire Tags'),
        ),
    ]
