# Generated by Django 4.0.4 on 2022-06-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        ('products', '0003_alter_unit_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='nodes.node', verbose_name='Node'),
        ),
    ]
