# Generated by Django 4.0.4 on 2022-06-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_alter_province_country_alter_tenantadmin_tenant_and_more'),
        ('products', '0005_unit_equivalent_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplychain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.supplychain', verbose_name='Supplychain'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='supplychain',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_chains', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity_units', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
