# Generated by Django 4.0.4 on 2022-06-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_supply_chain'),
        ('products', '0007_remove_supplychain_creator_remove_supplychain_tenant_and_more'),
        ('nodes', '0007_alter_connection_supplychain'),
        ('claims', '0025_alter_claim_supply_chains'),
        ('supply_chains', '0016_supplychain'),
        ('dashboard', '0004_alter_trackertheme_supply_chains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplychain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supply_chains.supplychain', verbose_name='Supplychain'),
        ),
        migrations.DeleteModel(
            name='SupplyChain',
        ),
    ]
