# Generated by Django 4.0.4 on 2022-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_supplychain_delete_supplychain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='batch',
            name='current_quantity_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Batch Current Quantity In KG'),
        ),
        migrations.AddField(
            model_name='batch',
            name='initial_quantity_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Batch Initial Quantity In KG'),
        ),
    ]
