# Generated by Django 4.0.4 on 2022-06-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplychain',
            new_name='supply_chain',
        ),
    ]
