# Generated by Django 4.0.4 on 2022-06-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_supplychain_product_supply_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
