# Generated by Django 4.0.4 on 2022-06-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
