# Generated by Django 4.0.4 on 2022-07-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_unit_tenant'),
    ]

    operations = [
    ]
