# Generated by Django 4.0.4 on 2022-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220713_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Unit Symbol'),
        ),
    ]
