# Generated by Django 4.0.4 on 2022-07-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Note'),
        ),
    ]
