# Generated by Django 4.0.4 on 2022-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_batch_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_uk',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_us',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_en_uk',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_en_us',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Unit'),
        ),
    ]
