# Generated by Django 4.0.4 on 2023-05-26 04:58

import common.library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_forms', '0027_formfieldvalue_submission_form_mongo_id_and_more'),
        ('tenants', '0044_tenant_product_grouping'),
        ('supply_chains', '0042_connection_submission_form_mongo_id'),
        ('products', '0018_product_is_processed_product_is_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_specific_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='dynamic_forms.formsubmission', verbose_name='Batch Specific Form Data'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_specific_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='dynamic_forms.formsubmission', verbose_name='Product Type Form Data'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Product Type')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=common.library._get_file_path, verbose_name='Photo')),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('batch_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_batch_form', to='dynamic_forms.formsubmission', verbose_name='Product Form Data')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('product_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_form', to='dynamic_forms.formsubmission', verbose_name='Product Form Data')),
                ('supply_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='supply_chains.supplychain', verbose_name='Supplychain')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='tenants.tenant', verbose_name='Tenant')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.producttype', verbose_name='Product Type'),
        ),
    ]
