# Generated by Django 4.0.4 on 2023-06-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0027_formfieldvalue_submission_form_mongo_id_and_more'),
        ('products', '0019_batch_batch_specific_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='batch_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_batch_form', to='dynamic_forms.form', verbose_name='Batch Form Data'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_form', to='dynamic_forms.form', verbose_name='Product Form Data'),
        ),
    ]
