# Generated by Django 4.0.4 on 2023-07-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0028_alter_formfield_form_alter_formfieldvalue_field_and_more'),
        ('nodes', '0036_alter_node_tenant_alter_nodedocument_file_and_more'),
        ('supply_chains', '0043_alter_nodesupplychain_node_alter_tag_tenant'),
        ('tenants', '0046_alter_category_tenant_alter_tenantadmin_tenant_and_more'),
        ('products', '0020_alter_producttype_batch_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='nodes.node', verbose_name='Node'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supply_chains.supplychain', verbose_name='Supplychain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='batch_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_batch_form', to='dynamic_forms.form', verbose_name='Batch Form'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_form', to='dynamic_forms.form', verbose_name='Product Form'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='supply_chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='supply_chains.supplychain', verbose_name='Supplychain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
    ]
