# Generated by Django 4.0.4 on 2023-07-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0028_alter_formfield_form_alter_formfieldvalue_field_and_more'),
        ('products', '0021_alter_batch_node_alter_batch_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='internal_form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_batch', to='dynamic_forms.formsubmission', verbose_name='Internal Batch Specific Form Data'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='internal_batch_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_batch_form', to='dynamic_forms.form', verbose_name='Internal Batch Form'),
        ),
    ]
