# Generated by Django 4.0.4 on 2023-07-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_batch_internal_form_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
