# Generated by Django 4.0.4 on 2022-07-11 18:59

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import v1.blockchain.models.callback_auth
import v1.blockchain.models.request


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('object_related_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('password', models.CharField(default=v1.blockchain.models.request.get_request_password, max_length=200)),
                ('body', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('receipt', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Discarded'), (4, 'Failed')], default=1)),
                ('last_api_call', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('response', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitMessageRequest',
            fields=[
                ('blockchainrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blockchain.blockchainrequest')),
            ],
            bases=('blockchain.blockchainrequest',),
        ),
        migrations.CreateModel(
            name='CallBackToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=v1.blockchain.models.callback_auth.get_key, max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Unused'), (2, 'Used'), (3, 'Invalidated')], default=1)),
                ('expiry', models.DateTimeField(default=v1.blockchain.models.callback_auth.get_expiry)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchainrequest')),
            ],
        ),
        migrations.AddField(
            model_name='blockchainrequest',
            name='callback_token',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='blockchain.callbacktoken'),
        ),
        migrations.AddField(
            model_name='blockchainrequest',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
