# Generated by Django 4.0.4 on 2022-05-18 11:53

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Options For Value'),
        ),
        migrations.AlterField(
            model_name='formfieldvalue',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to=common.library._get_file_path, verbose_name='File'),
        ),
    ]
