# Generated by Django 4.0.4 on 2022-06-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
        ('dynamic_forms', '0004_alter_formfieldvalue_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_forms', to='nodes.node', verbose_name='Node'),
        ),
    ]
