# Generated by Django 4.0.4 on 2022-06-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_alter_formsubmission_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='node',
        ),
    ]
