# Generated by Django 4.0.4 on 2022-06-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_remove_form_tenant_remove_formsubmission_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Options For Value'),
        ),
        migrations.AlterField(
            model_name='formfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dynamic_forms.formfield', verbose_name='Field'),
        ),
    ]
