# Generated by Django 4.0.4 on 2022-06-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0008_alter_formfield_form_alter_formfieldvalue_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.IntegerField(choices=[(101, 'Text'), (111, 'Paragraph'), (121, 'Check-Box'), (131, 'Radio Button'), (141, 'Drop Down'), (151, 'File'), (161, 'Date'), (171, 'Number'), (181, 'Email')], default=101, verbose_name='Field Type'),
        ),
    ]
