# Generated by Django 4.0.4 on 2022-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0009_alter_formfield_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='heading',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='formfield',
            old_name='description',
            new_name='place_holder',
        ),
        migrations.AddField(
            model_name='formfield',
            name='info',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='More Info'),
        ),
    ]
