# Generated by Django 4.0.4 on 2022-06-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0010_rename_heading_formfield_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='formfield',
            old_name='postion',
            new_name='position',
        ),
    ]
