# Generated by Django 4.0.4 on 2022-06-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0011_alter_formfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfieldvalue',
            options={'ordering': ['field__position']},
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.IntegerField(choices=[(101, 'Text'), (111, 'Number'), (121, 'Check-Box'), (131, 'Email'), (141, 'Paragraph'), (151, 'File'), (161, 'Date'), (171, 'Drop Down'), (181, 'Radio Button')], default=101, verbose_name='Field Type'),
        ),
    ]
