# Generated by Django 4.0.4 on 2022-06-10 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_forms', '0012_alter_formfieldvalue_options_alter_formfield_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='options',
        ),
        migrations.CreateModel(
            name='FieldValueOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Option')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Option')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Option Active')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formfieldvalue',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='field_values', to='dynamic_forms.fieldvalueoption', verbose_name='Selected Options'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='fields', to='dynamic_forms.fieldvalueoption', verbose_name='Options'),
        ),
    ]
