# Generated by Django 4.0.4 on 2022-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0014_formfield_width_alter_formfield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.IntegerField(choices=[(101, 'Text'), (111, 'Number'), (121, 'Email'), (131, 'Check-Box'), (141, 'Paragraph'), (151, 'File'), (161, 'Date'), (171, 'Drop Down'), (172, 'MultiSelect Drop Down'), (181, 'Radio Button')], default=101, verbose_name='Field Type'),
        ),
    ]
