# Generated by Django 4.0.4 on 2022-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0015_alter_formfield_position_alter_formfield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='place_holder',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Place Holder'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'key')},
        ),
    ]
