# Generated by Django 4.0.4 on 2022-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0016_alter_formfield_label_alter_formfield_place_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='width',
            field=models.IntegerField(choices=[(101, 'Small'), (111, 'Medium'), (121, 'Large')], default=111, verbose_name='Field Width'),
        ),
    ]
