# Generated by Django 4.0.4 on 2022-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0017_alter_formfield_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalue',
            name='file_hash',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='File hash'),
        ),
    ]
