# Generated by Django 4.0.4 on 2022-11-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0028_node_upload_timestamp'),
        ('dynamic_forms', '0020_alter_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalue',
            name='company_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.nodedocument'),
        ),
    ]
