# Generated by Django 4.0.4 on 2023-03-02 04:46

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0021_formfieldvalue_company_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='position',
            field=positions.fields.PositionField(default=-1, verbose_name='Position'),
        ),
    ]
