# Generated by Django 4.0.4 on 2023-04-26 11:27

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0023_form_description_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='position',
            field=positions.fields.PositionField(default=0, verbose_name='Position'),
        ),
    ]
