# Generated by Django 4.0.4 on 2023-04-26 11:28

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0024_alter_formfield_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='position',
            field=positions.fields.PositionField(default=1, verbose_name='Position'),
        ),
    ]
