# Generated by Django 4.0.4 on 2023-05-17 10:52

from django.db import migrations
from django.conf import settings

from v1.dynamic_forms.constants import mongo_db_models
from utilities.mongo_functions import create_collection


def create_collections(apps, schema_editor):
    """
    Function to create collection(tables) for form submission in mongodb.
    """
    for model in mongo_db_models:
        create_collection(model)


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0025_alter_formfield_position'),
    ]

    operations = [
        migrations.RunPython(create_collections)
    ]
