# Generated by Django 4.0.4 on 2023-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0026_auto_20230517_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalue',
            name='submission_form_mongo_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='MongoDB Form Submission Id'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='mongo_submission_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='MongoDB Form Submission Id'),
        ),
    ]
