# Generated by Django 4.0.4 on 2023-07-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0027_formfieldvalue_submission_form_mongo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_forms.form', verbose_name='Form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfieldvalue',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dynamic_forms.formfield', verbose_name='Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_forms', to='dynamic_forms.form', verbose_name='Form'),
            preserve_default=False,
        ),
    ]
